# Generated by Django 3.2.8 on 2021-10-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0002_park'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Park2',
        ),
    ]
